"""Add cascade delete

Revision ID: 9acec78b0964
Revises: f4b535063bcb
Create Date: 2025-11-15 15:14:34.678351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9acec78b0964'
down_revision = 'f4b535063bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('posts_poster_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'personel', ['poster_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('posts_poster_id_fkey'), 'personel', ['poster_id'], ['id'])

    # ### end Alembic commands ###
