"""fix about_author column type

Revision ID: a8bf4d6f7fd8
Revises: 35f1e0f62e33
Create Date: 2025-11-13 13:51:41.581426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8bf4d6f7fd8'
down_revision = '35f1e0f62e33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_author', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personel', schema=None) as batch_op:
        batch_op.drop_column('about_author')

    # ### end Alembic commands ###
